### ISSUE TITLE
Error schema in graph syncs for inspections

### ISSUE THREAD

**Issue by pacospace** [thoth-station/graph-sync-job#231]
**Describe the bug**
Error during inspections syncs due to schema validation.

**Screenshots**
```

2019-07-23 11:11:27,522 [1] CRITICAL root:111: Traceback (most recent call last):
--
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/result_base.py", line 94, in store_document
  | self.SCHEMA(document)
  | File "/opt/app-root/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 267, in __call__
  | return self._compiled([], data)
  | File "/opt/app-root/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
  | return base_validate(path, iteritems(data), out)
  | File "/opt/app-root/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 427, in validate_mapping
  | raise er.MultipleInvalid(errors)
  | voluptuous.error.MultipleInvalid: extra keys not allowed @ data['specification']['base']
  | The above exception was the direct cause of the following exception:
  | Traceback (most recent call last):
  | File "app.py", line 377, in <module>
  | cli()
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 764, in __call__
  | return self.main(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 717, in main
  | rv = self.invoke(ctx)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 956, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 555, in invoke
  | return callback(*args, **kwargs)
  | File "app.py", line 354, in cli
  | inspection_only_ceph_sync=inspection_only_ceph_sync,
  | File "app.py", line 215, in _do_sync
  | only_graph_sync=inspection_only_graph_sync,
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 303, in sync_inspection_documents
  | inspection_store.store_document(document)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/result_base.py", line 96, in store_document
  | raise SchemaError("Failed to validate document schema") from exc
  | thoth.storages.exceptions.SchemaError: Failed to validate document schema
  | Sentry is attempting to send 1 pending error messages
  | Waiting up to 2 seconds
  | Press Ctrl-C to quit
```

**Comment by fridex** [comment]
Fixed by https://github.com/thoth-station/storages/pull/829
