### ISSUE TITLE
Error on stage cluster - duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by fridex** [thoth-station/graph-sync-job#311]
```
---> Running application from Python script (app.py) ...
2019-11-06 12:10:32,953 [1] INFO     root:123: Setting up logging to a Sentry instance 'sentry.io/1298083', environment 'thoth-psi-stage'
2019-11-06 12:10:32,958 [1] INFO     root:160: Logging to rsyslog endpoint is turned off
2019-11-06 12:10:32,959 [1] INFO     thoth.graph_sync_job:225: graph-sync-job v0.5.3+storage.0.19.15.common.0.9.14 starting...
2019-11-06 12:10:33,006 [1] WARNING  py.warnings:99: /opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py:222: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got Engine(postgresql+psycopg2://thoth:***@postgresql.thoth-graph-stage.svc:5432/postgres?sslmode=disable)
  context = migration.MigrationContext.configure(self._engine)
2019-11-06 12:10:33,006 [1] INFO     alembic.runtime.migration:154: Context impl PostgresqlImpl.
2019-11-06 12:10:33,007 [1] INFO     alembic.runtime.migration:161: Will assume transactional DDL.
2019-11-06 12:10:33,315 [1] INFO     thoth.storages.sync:95: Syncing solver document from https://s3.upshift.redhat.com/ with id 'solver-rhel-8.0-py36-1208c085d1fd3ef3' to graph
2019-11-06 12:10:33,365 [1] INFO     thoth.storages.graph.postgres:4712: Syncing solver result of package 'gns3-gui' in version '1.3.3rc1' from 'https://pypi.org/simple' solved by {'os_name': 'rhel', 'os_version': '8.0', 'python_version': '3.6'}
2019-11-06 12:10:34,703 [1] INFO     thoth.storages.graph.postgres:4712: Syncing solver result of package 'gns3-gui' in version '1.3.3.dev1' from 'https://pypi.org/simple' solved by {'os_name': 'rhel', 'os_version': '8.0', 'python_version': '3.6'}
2019-11-06 12:10:34,719 [1] WARNING  thoth.storages.graph.models_base:60: Integrity error on creating a new record; this can be due to concurrent writes to database, recovering (attributes: {'package_name': 'gns3-gui', 'package_version': '1.3.3.dev1', 'python_package_index_id': 1, 'os_name': 'rhel', 'os_version': '8.0', 'python_version': '3.6', 'entity_id': 6898, 'python_package_metadata_id': 22552}): (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "python_package_version_package_name_package_version_python__key"
DETAIL:  Key (package_name, package_version, python_package_index_id, os_name, os_version, python_version)=(gns3-gui, 1.3.3.dev1, 1, rhel, 8.0, 3.6) already exists.
[SQL: INSERT INTO python_package_version (package_name, package_version, os_name, os_version, python_version, entity_id, python_package_index_id, python_package_metadata_id) VALUES (%(package_name)s, %(package_version)s, %(os_name)s, %(os_version)s, %(python_version)s, %(entity_id)s, %(python_package_index_id)s, %(python_package_metadata_id)s) RETURNING python_package_version.id]
[parameters: {'package_name': 'gns3-gui', 'package_version': '1.3.3.dev1', 'os_name': 'rhel', 'os_version': '8.0', 'python_version': '3.6', 'entity_id': 6898, 'python_package_index_id': 1, 'python_package_metadata_id': 22552}]
(Background on this error at: http://sqlalche.me/e/gkpj)
2019-11-06 12:10:34,864 [1] CRITICAL root:101: Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "python_package_version_package_name_package_version_python__key"
DETAIL:  Key (package_name, package_version, python_package_index_id, os_name, os_version, python_version)=(gns3-gui, 1.3.3.dev1, 1, rhel, 8.0, 3.6) already exists.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/models_base.py", line 52, in get_or_create
    session.commit()
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1137, in _emit_insert_statements
    statement, params
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "python_package_version_package_name_package_version_python__key"
DETAIL:  Key (package_name, package_version, python_package_index_id, os_name, os_version, python_version)=(gns3-gui, 1.3.3.dev1, 1, rhel, 8.0, 3.6) already exists.
[SQL: INSERT INTO python_package_version (package_name, package_version, os_name, os_version, python_version, entity_id, python_package_index_id, python_package_metadata_id) VALUES (%(package_name)s, %(package_version)s, %(os_name)s, %(os_version)s, %(python_version)s, %(entity_id)s, %(python_package_index_id)s, %(python_package_metadata_id)s) RETURNING python_package_version.id]
[parameters: {'package_name': 'gns3-gui', 'package_version': '1.3.3.dev1', 'os_name': 'rhel', 'os_version': '8.0', 'python_version': '3.6', 'entity_id': 6898, 'python_package_index_id': 1, 'python_package_metadata_id': 22552}]
(Background on this error at: http://sqlalche.me/e/gkpj)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "app.py", line 226, in <module>
    cli()
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 206, in cli
    inspection_only_ceph_sync=inspection_only_ceph_sync,
  File "app.py", line 115, in _do_sync
    amun_api_url=amun_api_url,
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 401, in sync_documents
    stats_change = handler(to_sync_document_id, force=force, graceful=graceful, graph=graph)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 99, in sync_solver_documents
    graph.sync_solver_result(document)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 4756, in sync_solver_result
    metadata=package_metadata
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 4012, in _create_python_package_version
    python_package_metadata_id=metadata.id if metadata else None
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/models_base.py", line 62, in get_or_create
    return session.query(cls).filter_by(**kwargs).one(), True
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3307, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
```

**Comment by goern** [comment]
is this still valid? if so -> reopen ;)
