### ISSUE TITLE
graph-sync via user-api seems to be broken

### ISSUE THREAD

**Issue by goern** [thoth-station/graph-sync-job#35]
```

---> Running application from Python script (app.py) ...
--
  | 2018-07-16 20:09:08,124 [1] INFO     root: Setting up logging to rsyslog endpoint rsyslog.dh-stage-ingest.svc:10514
  | 2018-07-16 20:09:08,213 [1] ERROR    root: RSYSLOG_HOST and RSYSLOG_PORT have been set but rsyslog.dh-stage-ingest.svc:10514 cannot be reached
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/logging.py", line 95, in init_logging
  | address=(_RSYSLOG_HOST, int(_RSYSLOG_PORT)))
  | File "/opt/app-root/lib/python3.6/site-packages/rfc5424logging/handler.py", line 120, in __init__
  | super(Rfc5424SysLogHandler, self).__init__(address, facility, socktype)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/handlers.py", line 831, in __init__
  | ress = socket.getaddrinfo(host, port, 0, socktype)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
  | for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
  | socket.gaierror: [Errno -2] Name or service not known
  | 2018-07-16 20:09:08,217 [1] INFO     thoth.graph_sync_job: graph-sync-job v0.4.0+thoth_storage.0.0.33 starting...
  | 2018-07-16 20:09:08,328 [1] INFO     thoth.graph_sync_job: Syncing solver results from None to ('janusgraph',)
  | 2018-07-16 20:09:08,337 [1] INFO     botocore.vendored.requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): storage-016.infra.prod.upshift.eng.rdu2.redhat.com
  | 2018-07-16 20:09:08,372 [1] INFO     thoth.graph_sync_job: Syncing solver document with id 'fridex-thoth-solver-fc27-thoth-solver-fc27-vv4qf' to graph
  | 2018-07-16 20:09:32,731 [1] CRITICAL root: Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/ceph.py", line 78, in retrieve_blob
  | return self._s3.Object(self.bucket, f"{self.prefix}/{object_key}").get()['Body'].read()
  | File "/opt/app-root/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
  | response = action(self, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
  | response = getattr(parent.meta.client, operation_name)(**params)
  | File "/opt/app-root/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
  | return self._make_api_call(operation_name, kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
  | raise error_class(parsed_response, operation_name)
  | botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: Unknown
  | The above exception was the direct cause of the following exception:
  | Traceback (most recent call last):
  | File "app.py", line 114, in <module>
  | cli()
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 722, in __call__
  | return self.main(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 697, in main
  | rv = self.invoke(ctx)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 895, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 535, in invoke
  | return callback(*args, **kwargs)
  | File "app.py", line 81, in cli
  | for document_id, document in solver_store.iterate_results():
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/ceph.py", line 88, in iterate_results
  | document = self.retrieve_document(document_id)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/ceph.py", line 93, in retrieve_document
  | return json.loads(self.retrieve_blob(document_id).decode())
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/ceph.py", line 82, in retrieve_blob
  | "Failed to retrieve object, object {!r} does not exist".format(object_key)) from exc
  | thoth.storages.exceptions.NotFoundError: Failed to retrieve object, object 'ridex-thoth-solver-fc26-thoth-solver-fc26-98rx4' does not exist

```

**Comment by fridex** [comment]
The recent changes made in storages fixed the issue and I cannot observe this with the user-api naming service changes - https://github.com/thoth-station/user-api/pull/167. Closing this - feel free to reopen if the issue persists.
