### ISSUE TITLE
graph-sync fail with missing positional argument issue

### ISSUE THREAD

**Issue by harshad16** [thoth-station/graph-sync-job#557]
**Describe the bug**
graph-sync fail with missing positional argument issue

```
Traceback (most recent call last):
  File "app.py", line 252, in <module>
    cli()
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 226, in cli
    _do_sync(
  File "app.py", line 125, in _do_sync
    stats = sync_documents(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/sync.py", line 574, in sync_documents
    stats_change = handler(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/sync.py", line 131, in sync_solver_documents
    graph.sync_solver_result(document)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/graph/postgres.py", line 4966, in sync_solver_result
{"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "transport", "lineno": 222, "funcname": "_send_event", "created": 1612317841.9203267, "asctime": "2021-02-03 02:04:01,920", "msecs": 920.3267097473145, "relative_created": 7674.7846603393555, "process": 1, "message": "Sending event, type:null level:error event_id:aee887547dc1484b8fd069fe75825db8 project:1298083 host:sentry.io"}
    os_version=normalize_os_version(os_version),
TypeError: normalize_os_version() missing 1 required positional argument: 'os_version'
```

**Comment by pacospace** [comment]
Fixed by: https://github.com/thoth-station/storages/pull/2212
